name: 漏洞反馈
description: 报错或漏洞请使用这个模板创建，不使用此模板创建的异常、漏洞相关issue将被直接关闭
title: "[Bug]: "
labels: ["bug?"]
body:
  - type: dropdown
    attributes:
      label: 部署方式
      description: "主程序使用的部署方式"
      options:
        - 手动部署
        - 安装器部署
        - 一键安装包部署
        - Docker部署
    validations:
      required: true
  - type: dropdown
    attributes:
      label: 登录框架
      description: "连接QQ使用的框架"
      options:
        - Mirai
        - go-cqhttp
    validations:
      required: false
  - type: input
    attributes:
      label: 系统环境
      description: 操作系统、系统架构。
      placeholder: 例如： CentOS x64、Windows11
    validations:
      required: true
  - type: input
    attributes:
      label: Python环境
      description: 运行程序的Python版本
      placeholder: 例如： Python 3.10
    validations:
      required: true
  - type: textarea
    attributes:
      label: 异常情况
      description: 完整描述异常情况，什么时候发生的、发生了什么
    validations:
      required: true
  - type: textarea
    attributes:
      label: 报错信息
      description: 请提供完整的**控制台**报错信息（若有）
    validations:
      required: false
