name: Update Wiki

on:
  pull_request:
    branches:
      - master
    paths:
      - 'res/wiki/**'
  push:
    branches:
      - master
    paths:
      - 'res/wiki/**'

jobs:
  update-wiki:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
    - name: Clone Wiki Repository
      uses: actions/checkout@v2
      with:
        repository: RockChinQ/QChatGPT.wiki
        path: wiki
    - name: Delete old wiki content
      run: |
        rm -rf wiki/*
    - name: Copy res/wiki content to wiki
      run: |
        cp -r res/wiki/* wiki/
    - name: Check for changes
      run: |
        cd wiki
        if git diff --quiet; then
          echo "No changes to commit."
          exit 0
        fi
    - name: Commit and Push Changes
      run: |
        cd wiki
        git add .
        git commit -m "Update wiki"
        git push
